### ISSUE TITLE
Documentation needed how to adjust the inputs and outputs for each Onnx model loaded

### ISSUE THREAD

**Issue by GeorgeS2019** [mat490/Godot-ONNX-AI-Models-Loaders#1]

**Comment by mat490** [comment]
Thanks for your feedback, this weekend I will expand the documentation to make it clearer how to adjust the inputs and outputs for each Onnx. I'll also see if there's a way to simplify it.

**Comment by mat490** [comment]
Did you have any problems trying to implement in your project?
